# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Ноутбуки',
                'verbose_name': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('CPU', models.CharField(db_index=True, max_length=200, verbose_name='Процессор')),
                ('RAM', models.CharField(db_index=True, max_length=200, verbose_name='RAM')),
                ('video', models.CharField(db_index=True, max_length=200, verbose_name='Видеокарта')),
                ('memory', models.CharField(db_index=True, max_length=200, verbose_name='Память')),
                ('screen', models.CharField(db_index=True, max_length=200, verbose_name='Экран')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='main.Category_notebook', verbose_name='Ноутбуки')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterIndexTogether(
            name='notebook',
            index_together=set([('id', 'slug')]),
        ),
    ]
