# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bigcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_notebook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.BigCategory', verbose_name='Категории'),
        ),
    ]
