# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_notebook_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_1', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_2', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_3', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_4', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_5', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category_notebook',
            options={'ordering': ['name'], 'verbose_name': 'Фирма Ноутбука', 'verbose_name_plural': 'Фирмы Ноутбуков'},
        ),
        migrations.AddField(
            model_name='complecting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complecting', to='main.Category_notebook', verbose_name='Комплюктующие'),
        ),
        migrations.AlterIndexTogether(
            name='complecting',
            index_together=set([('id', 'slug')]),
        ),
    ]
