# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170831_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_1', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_2', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 2')),
                ('property_3', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 3')),
                ('property_4', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 4')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acses', to='main.Category_notebook', verbose_name='Аксесуары')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincat4', to='main.BigCategory', verbose_name='Раздел')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Perf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_1', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 1')),
                ('property_2', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 2')),
                ('property_3', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 3')),
                ('property_4', models.CharField(db_index=True, max_length=200, verbose_name='Свойство 4')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perf', to='main.Category_notebook', verbose_name='Переферия')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincat3', to='main.BigCategory', verbose_name='Раздел')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='notebook',
            name='provider',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='complecting',
            name='property_2',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Свойство 2'),
        ),
        migrations.AlterField(
            model_name='complecting',
            name='property_3',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Свойство 3'),
        ),
        migrations.AlterField(
            model_name='complecting',
            name='property_4',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Свойство 4'),
        ),
        migrations.AlterField(
            model_name='complecting',
            name='property_5',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Свойство 5'),
        ),
        migrations.AlterIndexTogether(
            name='perf',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='acses',
            index_together=set([('id', 'slug')]),
        ),
    ]
