# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170903_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.time, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'db_table': 'ProductStat',
            },
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_1',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_2',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_3',
            field=models.CharField(db_index=True, max_length=200, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_4',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_5',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='property_6',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Экран'),
        ),
        migrations.AddField(
            model_name='productstat',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='main.Notebook', verbose_name='notw'),
        ),
    ]
