# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170904_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShakeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Товарик')),
                ('categoty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catshake', to='main.Category_notebook', verbose_name='Подразде')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincatshake', to='main.BigCategory', verbose_name='Раздел')),
            ],
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 5, 17, 58, 26, 122664, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
