# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171003_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_notebook',
            name='prop_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 3, 10, 52, 17, 656253, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название1'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='value',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Значение1'),
        ),
    ]
