# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171003_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acses_list', models.ManyToManyField(to='main.Acses')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PC', to='main.Category_notebook', verbose_name='Компьютеры')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincat5', to='main.BigCategory', verbose_name='Раздел')),
                ('perf_list', models.ManyToManyField(to='main.Perf')),
                ('property_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='main.Complecting', verbose_name='Процессор')),
                ('property_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RAM', to='main.Complecting', verbose_name='RAM')),
                ('property_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video', to='main.Complecting', verbose_name='Видеокарта')),
                ('property_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Memory', to='main.Complecting', verbose_name='Память')),
                ('property_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motherboard', to='main.Complecting', verbose_name='Материнска плата')),
                ('property_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BP', to='main.Complecting', verbose_name='Блок питания/Кейс')),
                ('property_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Case', to='main.Complecting', verbose_name='Блок питания/Кейс')),
                ('property_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cooler', to='main.Complecting', verbose_name='Система охлождения')),
                ('property_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DVD', to='main.Complecting', verbose_name='DVD')),
            ],
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 4, 7, 35, 56, 333356, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
