# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171004_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_notebook',
            options={'ordering': ['name'], 'verbose_name': 'Подкатегория товара', 'verbose_name_plural': 'Подкатегории товаров'},
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 5, 10, 28, 519682, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
