# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171005_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='main.Category_notebook', verbose_name='ГруппаНоутбуков')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubnotes', to='main.BigCategory', verbose_name='Хаб')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 6, 30, 8, 399322, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='main.HubNotebook', verbose_name='Модель'),
        ),
        migrations.AlterIndexTogether(
            name='hubnotebook',
            index_together=set([('id', 'slug')]),
        ),
    ]
