# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171123_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='main.Category_notebook', verbose_name='ГруппаPC')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubpc', to='main.BigCategory', verbose_name='ХабPC')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pc',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubPC', to='main.HubNotebook', verbose_name='МодельPC'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 24, 9, 1, 3, 685379, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterIndexTogether(
            name='hubpc',
            index_together=set([('id', 'slug')]),
        ),
    ]
