# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20171124_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubPC', to='main.HubPC', verbose_name='МодельPC'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 24, 9, 3, 24, 716968, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
