# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20171205_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='acses',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='complecting',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pc',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='perf',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 12, 2, 2, 467195, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
