# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171205_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubAcses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubacses_categoty', to='main.Category_notebook', verbose_name='ГруппаАксес')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubacses', to='main.BigCategory', verbose_name='ХабАксессуары')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HubComplecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubcomplecting_category', to='main.Category_notebook', verbose_name='ГруппаКОмплектующие')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubcomplecting', to='main.BigCategory', verbose_name='ХабКомплектуюшие')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HubPerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubperf_category', to='main.Category_notebook', verbose_name='ГруппаПереферия')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubperf', to='main.BigCategory', verbose_name='ХабПереферия')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 17, 55, 27, 301549, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterIndexTogether(
            name='hubperf',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='hubcomplecting',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='hubacses',
            index_together=set([('id', 'slug')]),
        ),
    ]
