# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20171205_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='acses',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='main.HubAcses', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='complecting',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='main.HubComplecting', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='perf',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='main.HubPerf', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 17, 56, 36, 997853, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
